package com.trainlog.analyzer.util

import com.trainlog.analyzer.data.model.TrainingRun

object ReportExporter {
    fun markdown(run: TrainingRun): String {
        val diagnoses = listOfNotNull(
            run.diagnosisFlat.takeIf { it }?.let { "Train & eval flat" },
            run.diagnosisOverfit.takeIf { it }?.let { "Overfitting" },
            run.diagnosisStillLearning.takeIf { it }?.let { "Masih belajar" },
            run.diagnosisNoisy.takeIf { it }?.let { "Noisy" },
            run.diagnosisDownstreamBad.takeIf { it }?.let { "Downstream jelek" }
        )
        val best = Calc.bestCheckpoint(run.checkpointNotes)
        return buildString {
            appendLine("# ${run.name.ifBlank { "Untitled Run" }}")
            appendLine()
            appendLine("**Status:** ${if (run.isPlateau) "Plateau" else "Training/review"}")
            appendLine("**Tanggal:** ${run.date}")
            appendLine("**Hardware:** ${run.hardware.ifBlank { "—" }}")
            appendLine("**Git:** `${run.gitCommit.ifBlank { "—" }}` · **Seed:** ${run.seed.ifBlank { "—" }}")
            if (run.parentRunName.isNotBlank()) appendLine("**Parent:** ${run.parentRunName}")
            appendLine()
            appendLine("## 1. Identitas")
            appendLine("- Host: ${run.hostname.ifBlank { "—" }}")
            appendLine("- Framework: ${run.frameworkVersions.ifBlank { "—" }}")
            if (run.configYaml.isNotBlank()) appendLine("\n```\n${run.configYaml}\n```")
            appendLine()
            appendLine("## 2. Model")
            appendLine("- Preset: ${run.architecturePreset.ifBlank { "—" }}")
            appendLine("- Layers/d/heads: ${run.numLayers}/${run.embedDim}/${run.numHeads}")
            appendLine("- Vocab: ${run.vocabSize.ifBlank { "—" }}")
            appendLine("- Params: ${run.totalParams.ifBlank { "—" }} (trainable ${run.trainableParams.ifBlank { "—" }})")
            appendLine("- Precision/attn: ${run.precision} / ${run.attnImpl}")
            appendLine("- Resume: ${run.resumeFrom.ifBlank { "—" }}")
            appendLine("- GaLore rank/gap: ${run.galoreRank}/${run.galoreGap} · LoRA: ${run.loraRank}")
            if (run.initNotes.isNotBlank()) appendLine("- Init: ${run.initNotes}")
            appendLine()
            appendLine("## 3. Data")
            appendLine("- Sources: ${run.dataSources.ifBlank { "—" }}")
            appendLine("- Seq ${run.seqLen} · global batch ${run.globalBatch} · micro ${run.microBatch} × accum ${run.gradAccum} · ${run.numGpus} devices")
            appendLine("- Packing: ${run.packingEfficiency.ifBlank { "—" }}")
            appendLine("- Tokens: ${run.tokensEstimate.ifBlank { "—" }} · epoch eq. ${run.epochEquivalent.ifBlank { "—" }}")
            appendLine("- Mixture: ${run.mixtureWeights.ifBlank { "—" }}")
            appendLine("- Per domain: ${run.tokensPerDomain.ifBlank { "—" }}")
            appendLine("- Held-out: ${run.heldOutSize.ifBlank { "—" }}")
            appendLine()
            appendLine("## 4. Optim")
            appendLine("- ${run.optimizer}: LR ${run.lrMax}→${run.lrMin}, warmup ${run.warmupSteps}, ${run.scheduleType}")
            appendLine("- WD ${run.weightDecay} · clip ${run.gradClip}")
            appendLine("- Last LR ${run.lastLr} · grad norm ${run.lastGradNorm}")
            appendLine()
            appendLine("## 5. Learning curve")
            appendLine("- Steps: ${run.totalSteps.ifBlank { "—" }}")
            appendLine("- Train: ${run.finalTrainLoss.ifBlank { "—" }} · Eval: ${run.finalEvalLoss.ifBlank { "—" }} · Best: ${run.bestEvalLoss.ifBlank { "—" }}")
            appendLine("- Rel. improvement: ${run.relativeImprovement.ifBlank { "—" }}%")
            appendLine("- Gap: ${run.trainEvalGap.ifBlank { "—" }} · PPL: ${run.perplexity.ifBlank { "—" }} · Noise: ${run.noiseLevel}")
            appendLine()
            appendLine("## 6. Compute")
            appendLine("- Sec/step: ${run.secPerStep.ifBlank { "—" }} · tok/s: ${run.tokensPerSec.ifBlank { "—" }}")
            appendLine("- FLOPs: ${run.flopsEstimate.ifBlank { "—" }} · MFU: ${run.mfuPercent.ifBlank { "—" }}%")
            appendLine("- Wall: ${run.wallClockHours.ifBlank { "—" }} h · GPU-h: ${run.gpuHours.ifBlank { "—" }} · Cost: ${run.estimatedCost.ifBlank { "—" }}")
            appendLine()
            appendLine("## 7. Downstream")
            if (run.task1Name.isNotBlank()) appendLine("- ${run.task1Name}: ${run.task1Result}")
            if (run.task2Name.isNotBlank()) appendLine("- ${run.task2Name}: ${run.task2Result}")
            if (run.task3Name.isNotBlank()) appendLine("- ${run.task3Name}: ${run.task3Result}")
            appendLine("- Forgetting: ${if (run.hasForgetting) "Ya — ${run.forgettingNote}" else "Aman"}")
            appendLine("- Harness: ${run.evalHarness.ifBlank { "—" }}")
            if (run.sampleNotes.isNotBlank()) appendLine("- Samples: ${run.sampleNotes}")
            appendLine()
            appendLine("## 8. Checkpoints")
            appendLine("- Final: ${run.finalCheckpoint.ifBlank { "—" }}")
            appendLine("- Best: ${run.bestCheckpoint.ifBlank { best?.first ?: "—" }}")
            if (best != null) appendLine("- Auto-best: ${best.first} (loss ${best.second})")
            if (run.checkpointNotes.isNotBlank()) appendLine("\n```\n${run.checkpointNotes}\n```")
            appendLine()
            appendLine("## 9. Diagnosis & keputusan")
            diagnoses.forEach { appendLine("- $it") }
            if (run.rootCause.isNotBlank()) appendLine("\nAkar: ${run.rootCause}")
            appendLine("\n**Hipotesis:** ${run.hypothesis.ifBlank { "—" }}")
            appendLine("**Perubahan:** ${run.whatChanged.ifBlank { "—" }}")
            appendLine("**Keputusan:** ${run.decision.ifBlank { "—" }}")
            appendLine("**Priority:** ${run.priority}")
            appendLine("\n${run.conclusion.ifBlank { "—" }}")
            appendLine()
            appendLine("## 10. Failures")
            appendLine(run.failureNotes.ifBlank { "—" })
            appendLine()
            appendLine("---")
            appendLine("*Generated by TrainLog*")
        }
    }
}
