package com.trainlog.analyzer.util

import com.trainlog.analyzer.data.model.TrainingRun

object ReportExporter {
    fun markdown(run: TrainingRun): String {
        val diagnoses = listOfNotNull(
            run.diagnosisFlat.takeIf { it }?.let { "Train & eval flat" },
            run.diagnosisOverfit.takeIf { it }?.let { "Overfitting" },
            run.diagnosisStillLearning.takeIf { it }?.let { "Masih belajar" },
            run.diagnosisNoisy.takeIf { it }?.let { "Noisy" },
            run.diagnosisDownstreamBad.takeIf { it }?.let { "Downstream jelek" }
        )
        val best = Calc.bestCheckpoint(run.checkpointNotes)
        return buildString {
            appendLine("# ${run.name.ifBlank { "Untitled Run" }}")
            appendLine()
            appendLine("**Tanggal:** ${run.date}")
            appendLine("**Steps:** ${run.totalSteps.ifBlank { "—" }}")
            appendLine("**Preset:** ${run.architecturePreset.ifBlank { "—" }}")
            appendLine("**Status:** ${if (run.isPlateau) "Plateau" else "Masih belajar"}")
            if (run.plateauAlert) appendLine("**Alert:** Plateau terdeteksi")
            if (run.parentRunName.isNotBlank()) appendLine("**Parent run:** ${run.parentRunName}")
            appendLine()
            appendLine("## Learning curve")
            appendLine("- Train: ${run.finalTrainLoss.ifBlank { "—" }}")
            appendLine("- Eval: ${run.finalEvalLoss.ifBlank { "—" }}")
            appendLine("- Best eval: ${run.bestEvalLoss.ifBlank { "—" }}")
            appendLine("- Rel. improvement: ${run.relativeImprovement.ifBlank { "—" }}%")
            appendLine("- Gap: ${run.trainEvalGap.ifBlank { "—" }}")
            appendLine("- PPL: ${run.perplexity.ifBlank { "—" }}")
            appendLine()
            appendLine("## Downstream")
            if (run.task1Name.isNotBlank()) appendLine("- ${run.task1Name}: ${run.task1Result}")
            if (run.task2Name.isNotBlank()) appendLine("- ${run.task2Name}: ${run.task2Result}")
            if (run.task3Name.isNotBlank()) appendLine("- ${run.task3Name}: ${run.task3Result}")
            appendLine("- Forgetting: ${if (run.hasForgetting) "Ya — ${run.forgettingNote}" else "Aman"}")
            appendLine()
            appendLine("## Diagnosis")
            diagnoses.forEach { appendLine("- $it") }
            if (run.rootCause.isNotBlank()) appendLine("\nAkar masalah: ${run.rootCause}")
            appendLine()
            appendLine("## Checkpoints")
            appendLine("- Final: ${run.finalCheckpoint.ifBlank { "—" }}")
            appendLine("- Best: ${run.bestCheckpoint.ifBlank { best?.first ?: "—" }}")
            if (best != null) appendLine("- Auto-best dari notes: ${best.first} (loss ${best.second})")
            if (run.checkpointNotes.isNotBlank()) appendLine("- Notes:\n```\n${run.checkpointNotes}\n```")
            appendLine()
            appendLine("## Keputusan")
            appendLine(run.decision.ifBlank { "—" })
            appendLine()
            appendLine("## Eksperimen")
            appendLine("- Hipotesis: ${run.hypothesis.ifBlank { "—" }}")
            appendLine("- Perubahan: ${run.whatChanged.ifBlank { "—" }}")
            appendLine("- Priority: ${run.priority}")
            appendLine()
            appendLine("## Compute")
            appendLine("- Tokens est.: ${run.tokensEstimate.ifBlank { "—" }}")
            appendLine("- FLOPs est.: ${run.flopsEstimate.ifBlank { "—" }}")
            appendLine("- Sec/step: ${run.secPerStep.ifBlank { "—" }}")
            appendLine()
            appendLine("## Kesimpulan")
            appendLine(run.conclusion.ifBlank { "—" })
            appendLine()
            appendLine("---")
            appendLine("*Generated by TrainLog*")
        }
    }
}
